version: '3.1'

services:

  php-fpm:
    build: ./docker/php
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /app
    container_name: 'php-fpm'
    environment:
      PHP_IDE_CONFIG: serverName=docker
    restart: always

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    depends_on:
      - php-fpm
    ports:
      - '8080:80'
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  mysql:
    image: mysql
    container_name: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: management_system
    ports:
      - '3306:3306'
