version: '3.1'

services:

  php-fpm:
    build: ./docker/php
    volumes:
      - .:/app
    working_dir: /app
    container_name: 'php-fpm'
    environment:
      PHP_IDE_CONFIG: serverName=docker
    restart: always

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    depends_on:
      - php-fpm
    ports:
      - '8080:80'
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  mysql:
    image: mysql
    container_name: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: management_system
    ports:
      - '3306:3306'

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
